title: 3D60<sup>o</sup> Dataset
description: 3D Vision Indoors Spherical Panoramas
show_downloads: true
theme: jekyll-theme-architect

github:
  form_url: https://forms.gle/ikJW2QU88GDahEBr6
  zenodo_url: ./download.html
  owner_url: https://zokin.github.io
  owner_name: Nikolaos Zioulis  
  
google_analytics: UA-147231916-1
